export const ALL_ADMINS_REQUEST = 'ALL_ADMINS_REQUEST';
export const ALL_ADMINS_SUCCESS = 'ALL_ADMINS_SUCCESS';
export const ALL_ADMINS_FAIL = 'ALL_ADMINS_FAIL';

export const ADMIN_DETAILS_REQUEST = 'ADMIN_DETAILS_REQUEST'
export const ADMIN_DETAILS_SUCCESS = 'ADMIN_DETAILS_SUCCESS'
export const ADMIN_DETAILS_FAIL = 'ADMIN_DETAILS_FAIL'

export const UPDATE_ADMIN_REQUEST = 'UPDATE_ADMIN_REQUEST'
export const UPDATE_ADMIN_SUCCESS = 'UPDATE_ADMIN_SUCCESS'
export const UPDATE_ADMIN_RESET = 'UPDATE_ADMIN_RESET'
export const UPDATE_ADMIN_FAIL = 'UPDATE_ADMIN_FAIL'

export const SUPER_ADMIN_REQUEST = 'SUPER_ADMIN_REQUEST'
export const SUPER_ADMIN_SUCCESS = 'SUPER_ADMIN_SUCCESS'
export const SUPER_ADMIN_RESET = 'SUPER_ADMIN_RESET'
export const SUPER_ADMIN_FAIL = 'SUPER_ADMIN_FAIL'

export const DEACTIVATE_ADMIN_REQUEST = 'DEACTIVATE_ADMIN_REQUEST'
export const DEACTIVATE_ADMIN_SUCCESS = 'DEACTIVATE_ADMIN_SUCCESS'
export const DEACTIVATE_ADMIN_RESET = 'DEACTIVATE_ADMIN_RESET'
export const DEACTIVATE_ADMIN_FAIL = 'DEACTIVATE_ADMIN_FAIL'

export const ACTIVATE_ADMIN_REQUEST = 'ACTIVATE_ADMIN_REQUEST'
export const ACTIVATE_ADMIN_SUCCESS = 'ACTIVATE_ADMIN_SUCCESS'
export const ACTIVATE_ADMIN_RESET = 'ACTIVATE_ADMIN_RESET'
export const ACTIVATE_ADMIN_FAIL = 'ACTIVATE_ADMIN_FAIL'

export const DELETE_ADMIN_REQUEST = 'DELETE_ADMIN_REQUEST'
export const DELETE_ADMIN_SUCCESS = 'DELETE_ADMIN_SUCCESS'
export const DELETE_ADMIN_RESET = 'DELETE_ADMIN_RESET'
export const DELETE_ADMIN_FAIL = 'DELETE_ADMIN_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'