export const LOGIN_GUEST_REQUEST = 'LOGIN_GUEST_REQUEST'
export const LOGIN_GUEST_SUCCESS = 'LOGIN_GUEST_SUCCESS'
export const LOGIN_GUEST_FAIL = 'LOGIN_GUEST_FAIL'

export const REGISTER_GUEST_REQUEST = 'REGISTER_GUEST_REQUEST'
export const REGISTER_GUEST_SUCCESS = 'REGISTER_GUEST_SUCCESS'
export const REGISTER_GUEST_FAIL = 'REGISTER_GUEST_FAIL'

export const ACTIVATE_GUEST_REQUEST = 'ACTIVATE_GUEST_REQUEST'
export const ACTIVATE_GUEST_SUCCESS = 'ACTIVATE_GUEST_SUCCESS'
export const ACTIVATE_GUEST_FAIL = 'ACTIVATE_GUEST_FAIL'

export const LOAD_GUEST_REQUEST = 'LOAD_GUEST_REQUEST'
export const LOAD_GUEST_SUCCESS = 'LOAD_GUEST_SUCCESS'
export const LOAD_GUEST_FAIL = 'LOAD_GUEST_FAIL'

export const GET_TOKEN_GUEST_REQUEST = 'GET_TOKEN_GUEST_REQUEST'
export const GET_TOKEN_GUEST_SUCCESS = 'GET_TOKEN_GUEST_SUCCESS'
export const GET_TOKEN_GUEST_FAIL = 'GET_TOKEN_GUEST_FAIL'

export const LOGOUT_GUEST_REQUEST = 'LOGOUT_GUEST_REQUEST'
export const LOGOUT_GUEST_SUCCESS = 'LOGOUT_GUEST_SUCCESS'
export const LOGOUT_GUEST_FAIL = 'LOGOUT_GUEST_FAIL'

export const FORGOT_PASSWORD_GUEST_REQUEST = 'FORGOT_PASSWORD_GUEST_REQUEST'
export const FORGOT_PASSWORD_GUEST_SUCCESS = 'FORGOT_PASSWORD_GUEST_SUCCESS'
export const FORGOT_PASSWORD_GUEST_FAIL = 'FORGOT_PASSWORD_GUEST_FAIL'

export const RESET_PASSWORD_GUEST_REQUEST = 'RESET_PASSWORD_GUEST_REQUEST'
export const RESET_PASSWORD_GUEST_SUCCESS = 'RESET_PASSWORD_GUEST_SUCCESS'
export const RESET_PASSWORD_GUEST_FAIL = 'RESET_PASSWORD_GUEST_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'