export const LOGIN_ADMIN_REQUEST = 'LOGIN_ADMIN_REQUEST'
export const LOGIN_ADMIN_SUCCESS = 'LOGIN_ADMIN_SUCCESS'
export const LOGIN_ADMIN_FAIL = 'LOGIN_ADMIN_FAIL'

export const REGISTER_ADMIN_REQUEST = 'REGISTER_ADMIN_REQUEST'
export const REGISTER_ADMIN_SUCCESS = 'REGISTER_ADMIN_SUCCESS'
export const REGISTER_ADMIN_FAIL = 'REGISTER_ADMIN_FAIL'
export const REGISTER_ADMIN_RESET = 'REGISTER_ADMIN_RESET'

export const ACTIVATE_ADMIN_REQUEST = 'ACTIVATE_ADMIN_REQUEST'
export const ACTIVATE_ADMIN_SUCCESS = 'ACTIVATE_ADMIN_SUCCESS'
export const ACTIVATE_ADMIN_FAIL = 'ACTIVATE_ADMIN_FAIL'

export const LOAD_ADMIN_REQUEST = 'LOAD_ADMIN_REQUEST'
export const LOAD_ADMIN_SUCCESS = 'LOAD_ADMIN_SUCCESS'
export const LOAD_ADMIN_FAIL = 'LOAD_ADMIN_FAIL'

export const GET_ADMIN_TOKEN_REQUEST = 'GET_ADMIN_TOKEN_REQUEST'
export const GET_ADMIN_TOKEN_SUCCESS = 'GET_ADMIN_TOKEN_SUCCESS'
export const GET_ADMIN_TOKEN_FAIL = 'GET_ADMIN_TOKEN_FAIL'

export const LOGOUT_ADMIN_REQUEST = 'LOGOUT_ADMIN_REQUEST'
export const LOGOUT_ADMIN_SUCCESS = 'LOGOUT_ADMIN_SUCCESS'
export const LOGOUT_ADMIN_FAIL = 'LOGOUT_ADMIN_FAIL'

export const FORGOT_PASSWORD_ADMIN_REQUEST = 'FORGOT_PASSWORD_ADMIN_REQUEST'
export const FORGOT_PASSWORD_ADMIN_SUCCESS = 'FORGOT_PASSWORD_ADMIN_SUCCESS'
export const FORGOT_PASSWORD_ADMIN_FAIL = 'FORGOT_PASSWORD_ADMIN_FAIL'

export const RESET_PASSWORD_ADMIN_REQUEST = 'RESET_PASSWORD_ADMIN_REQUEST'
export const RESET_PASSWORD_ADMIN_SUCCESS = 'RESET_PASSWORD_ADMIN_SUCCESS'
export const RESET_PASSWORD_ADMIN_FAIL = 'RESET_PASSWORD_ADMIN_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'