export const ALL_BOOKMARK_REQUEST = 'ALL_BOOKMARK_REQUEST'
export const ALL_BOOKMARK_SUCCESS = 'ALL_BOOKMARK_SUCCESS'
export const ALL_BOOKMARK_FAIL = 'ALL_BOOKMARK_FAIL'

export const USER_BOOKMARK_REQUEST = 'USER_BOOKMARK_REQUEST'
export const USER_BOOKMARK_SUCCESS = 'USER_BOOKMARK_SUCCESS'
export const USER_BOOKMARK_FAIL = 'USER_BOOKMARK_FAIL'

export const NEW_BOOKMARK_REQUEST = 'NEW_BOOKMARK_REQUEST'
export const NEW_BOOKMARK_SUCCESS = 'NEW_BOOKMARK_SUCCESS'
export const NEW_BOOKMARK_RESET = 'NEW_BOOKMARK_RESET'
export const NEW_BOOKMARK_FAIL = 'NEW_BOOKMARK_FAIL'

export const DELETE_BOOKMARK_REQUEST = 'DELETE_BOOKMARK_REQUEST'
export const DELETE_BOOKMARK_SUCCESS = 'DELETE_BOOKMARK_SUCCESS'
export const DELETE_BOOKMARK_RESET = 'DELETE_BOOKMARK_RESET'
export const DELETE_BOOKMARK_FAIL = 'DELETE_BOOKMARK_FAIL'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'