export const ALL_BORROW_REQUEST = 'ALL_BORROW_REQUEST'
export const ALL_BORROW_SUCCESS = 'ALL_BORROW_SUCCESS'
export const ALL_BORROW_FAIL = 'ALL_BORROW_FAIL'

export const ALL_STUDENT_BORROW_REQUEST = 'ALL_STUDENT_BORROW_REQUEST'
export const ALL_STUDENT_BORROW_SUCCESS = 'ALL_STUDENT_BORROW_SUCCESS'
export const ALL_STUDENT_BORROW_FAIL = 'ALL_STUDENT_BORROW_FAIL'

export const NEW_BORROW_REQUEST = 'NEW_BORROW_REQUEST'
export const NEW_BORROW_SUCCESS = 'NEW_BORROW_SUCCESS'
export const NEW_BORROW_RESET = 'NEW_BORROW_RESET'
export const NEW_BORROW_FAIL = 'NEW_BORROW_FAIL'

export const STUDENT_BORROW_REQUEST = 'STUDENT_BORROW_REQUEST'
export const STUDENT_BORROW_SUCCESS = 'STUDENT_BORROW_SUCCESS'
export const STUDENT_BORROW_RESET = 'STUDENT_BORROW_RESET'
export const STUDENT_BORROW_FAIL = 'STUDENT_BORROW_FAIL'

export const UPDATE_BORROW_REQUEST = 'UPDATE_BORROW_REQUEST'
export const UPDATE_BORROW_SUCCESS = 'UPDATE_BORROW_SUCCESS'
export const UPDATE_BORROW_RESET = 'UPDATE_BORROW_RESET'
export const UPDATE_BORROW_FAIL = 'UPDATE_BORROW_FAIL'

export const DELETE_BORROW_REQUEST = 'DELETE_BORROW_REQUEST'
export const DELETE_BORROW_SUCCESS = 'DELETE_BORROW_SUCCESS'
export const DELETE_BORROW_RESET = 'DELETE_BORROW_RESET'
export const DELETE_BORROW_FAIL = 'DELETE_BORROW_FAIL'

export const VERIFY_BORROW_REQUEST = "VERIFY_BORROW_REQUEST";
export const VERIFY_BORROW_SUCCESS = "VERIFY_BORROW_SUCCESS";
export const VERIFY_BORROW_FAIL = "VERIFY_BORROW_FAIL";
export const VERIFY_BORROW_RESET = "VERIFY_BORROW_RESET";

export const DECLINE_BORROW_REQUEST = "DECLINE_BORROW_REQUEST";
export const DECLINE_BORROW_SUCCESS = "DECLINE_BORROW_SUCCESS";
export const DECLINE_BORROW_FAIL = "DECLINE_BORROW_FAIL";
export const DECLINE_BORROW_RESET = "DECLINE_BORROW_RESET";

export const CLEAR_ERRORS = 'CLEAR_ERRORS'