export const ALL_BORROW_REQUEST = 'ALL_BORROW_REQUEST'
export const ALL_BORROW_SUCCESS = 'ALL_BORROW_SUCCESS'
export const ALL_BORROW_FAIL = 'ALL_BORROW_FAIL'

export const NEW_BORROW_REQUEST = 'NEW_BORROW_REQUEST'
export const NEW_BORROW_SUCCESS = 'NEW_BORROW_SUCCESS'
export const NEW_BORROW_RESET = 'NEW_BORROW_RESET'
export const NEW_BORROW_FAIL = 'NEW_BORROW_FAIL'

export const UPDATE_BORROW_REQUEST = 'UPDATE_BORROW_REQUEST'
export const UPDATE_BORROW_SUCCESS = 'UPDATE_BORROW_SUCCESS'
export const UPDATE_BORROW_RESET = 'UPDATE_BORROW_RESET'
export const UPDATE_BORROW_FAIL = 'UPDATE_BORROW_FAIL'

export const DELETE_BORROW_REQUEST = 'DELETE_BORROW_REQUEST'
export const DELETE_BORROW_SUCCESS = 'DELETE_BORROW_SUCCESS'
export const DELETE_BORROW_RESET = 'DELETE_BORROW_RESET'
export const DELETE_BORROW_FAIL = 'DELETE_BORROW_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'