export const ALL_COURSE_REQUEST = 'ALL_COURSE_REQUEST'
export const ALL_COURSE_SUCCESS = 'ALL_COURSE_SUCCESS'
export const ALL_COURSE_FAIL = 'ALL_COURSE_FAIL'

export const NEW_COURSE_REQUEST = 'NEW_COURSE_REQUEST'
export const NEW_COURSE_SUCCESS = 'NEW_COURSE_SUCCESS'
export const NEW_COURSE_RESET = 'NEW_COURSE_RESET'
export const NEW_COURSE_FAIL = 'NEW_COURSE_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'