
export const ALL_DEPARTMENT_REQUEST= "ALL_DEPARTMENT_REQUEST"
export const ALL_DEPARTMENT_SUCCESS= "ALL_DEPARTMENT_SUCCESS"
export const ALL_DEPARTMENT_FAIL= "ALL_DEPARTMENT_FAIL"
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
