export const ALL_DEPT_REQUEST = 'ALL_DEPT_REQUEST'
export const ALL_DEPT_SUCCESS = 'ALL_DEPT_SUCCESS'
export const ALL_DEPT_FAIL = 'ALL_DEPT_FAIL'

export const NEW_DEPT_REQUEST = 'NEW_DEPT_REQUEST'
export const NEW_DEPT_SUCCESS = 'NEW_DEPT_SUCCESS'
export const NEW_DEPT_RESET = 'NEW_DEPT_RESET'
export const NEW_DEPT_FAIL = 'NEW_DEPT_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'