export const ALL_GUESTS_REQUEST = 'ALL_GUESTS_REQUEST';
export const ALL_GUESTS_SUCCESS = 'ALL_GUESTS_SUCCESS';
export const ALL_GUESTS_FAIL = 'ALL_GUESTS_FAIL';

export const GUEST_DETAILS_REQUEST = 'GUEST_DETAILS_REQUEST'
export const GUEST_DETAILS_SUCCESS = 'GUEST_DETAILS_SUCCESS'
export const GUEST_DETAILS_FAIL = 'GUEST_DETAILS_FAIL'

export const UPDATE_GUEST_REQUEST = 'UPDATE_GUEST_REQUEST'
export const UPDATE_GUEST_SUCCESS = 'UPDATE_GUEST_SUCCESS'
export const UPDATE_GUEST_RESET = 'UPDATE_GUEST_RESET'
export const UPDATE_GUEST_FAIL = 'UPDATE_GUEST_FAIL'

export const DEACTIVATE_GUEST_REQUEST = 'DEACTIVATE_GUEST_REQUEST'
export const DEACTIVATE_GUEST_SUCCESS = 'DEACTIVATE_GUEST_SUCCESS'
export const DEACTIVATE_GUEST_RESET = 'DEACTIVATE_GUEST_RESET'
export const DEACTIVATE_GUEST_FAIL = 'DEACTIVATE_GUEST_FAIL'

export const DELETE_GUEST_REQUEST = 'DELETE_GUEST_REQUEST'
export const DELETE_GUEST_SUCCESS = 'DELETE_GUEST_SUCCESS'
export const DELETE_GUEST_RESET = 'DELETE_GUEST_RESET'
export const DELETE_GUEST_FAIL = 'DELETE_GUEST_FAIL'

export const RESTORE_GUEST_REQUEST = 'RESTORE_GUEST_REQUEST'
export const RESTORE_GUEST_SUCCESS = 'RESTORE_GUEST_SUCCESS'
export const RESTORE_GUEST_RESET = 'RESTORE_GUEST_RESET'
export const RESTORE_GUEST_FAIL = 'RESTORE_GUEST_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'