export const VIEW_LOG_REQUEST = 'VIEW_LOG_REQUEST';
export const VIEW_LOG_SUCCESS = 'VIEW_LOG_SUCCESS';
export const VIEW_LOG_FAIL = 'VIEW_LOG_FAIL';

export const SEARCH_LOG_REQUEST = 'SEARCH_LOG_REQUEST';
export const SEARCH_LOG_SUCCESS = 'SEARCH_LOG_SUCCESS';
export const SEARCH_LOG_FAIL = 'SEARCH_LOG_FAIL';

export const DOWNLOAD_LOG_REQUEST = 'DOWNLOAD_LOG_REQUEST';
export const DOWNLOAD_LOG_SUCCESS = 'DOWNLOAD_LOG_SUCCESS';
export const DOWNLOAD_LOG_FAIL = 'DOWNLOAD_LOG_FAIL';

export const FETCH_LOGS_REQUEST = 'FETCH_LOGS_REQUEST';
export const FETCH_LOGS_SUCCESS = 'FETCH_LOGS_SUCCESS';
export const FETCH_LOGS_FAIL = 'FETCH_LOGS_FAIL';

export const DATA_COUNT_REQUEST = 'DATA_COUNT_REQUEST';
export const DATA_COUNT_SUCCESS = 'DATA_COUNT_SUCCESS';
export const DATA_COUNT_FAIL = 'DATA_COUNT_FAIL';

export const HOME_COUNT_REQUEST = 'HOME_COUNT_REQUEST';
export const HOME_COUNT_SUCCESS = 'HOME_COUNT_SUCCESS';
export const HOME_COUNT_FAIL = 'HOME_COUNT_FAIL';

export const FEATURED_COUNT_REQUEST = 'FEATURED_COUNT_REQUEST';
export const FEATURED_COUNT_SUCCESS = 'FEATURED_COUNT_SUCCESS';
export const FEATURED_COUNT_FAIL = 'FEATURED_COUNT_FAIL';

export const STUDENT_COUNT_REQUEST = 'STUDENT_COUNT_REQUEST';
export const STUDENT_COUNT_SUCCESS = 'STUDENT_COUNT_SUCCESS';
export const STUDENT_COUNT_FAIL = 'STUDENT_COUNT_FAIL';

export const GUEST_COUNT_REQUEST = 'GUEST_COUNT_REQUEST';
export const GUEST_COUNT_SUCCESS = 'GUEST_COUNT_SUCCESS';
export const GUEST_COUNT_FAIL = 'GUEST_COUNT_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS'