export const SUBSCRIBE_USER_REQUEST = "SUBSCRIBE_USER_REQUEST";
export const SUBSCRIBE_USER_SUCCESS = "SUBSCRIBE_USER_SUCCESS";
export const SUBSCRIBE_USER_FAIL = "SUBSCRIBE_USER_FAIL";
export const SUBSCRIBE_USER_RESET = "SUBSCRIBE_USER_RESET";

export const DELETE_SUBSCRIBE_REQUEST = "DELETE_SUBSCRIBE_REQUEST";
export const DELETE_SUBSCRIBE_SUCCESS = "DELETE_SUBSCRIBE_SUCCESS";
export const DELETE_SUBSCRIBE_FAIL = "DELETE_SUBSCRIBE_FAIL";
export const DELETE_SUBSCRIBE_RESET = "DELETE_SUBSCRIBE_RESET";

export const CLEAR_ERRORS = 'CLEAR_ERRORS'