
export const ALL_THESIS_REQUEST= "ALL_THESIS_REQUEST"
export const ALL_THESIS_SUCCESS= "ALL_THESIS_SUCCESS"
export const ALL_THESIS_FAIL= "ALL_THESIS_FAIL"

export const ALL_STUDENT_THESIS_REQUEST= "ALL_STUDENT_THESIS_REQUEST"
export const ALL_STUDENT_THESIS_SUCCESS= "ALL_STUDENT_THESIS_SUCCESS"
export const ALL_STUDENT_THESIS_FAIL= "ALL_STUDENT_THESIS_FAIL"

export const ALL_ADMIN_THESIS_REQUEST= "ALL_ADMIN_THESIS_REQUEST"
export const ALL_ADMIN_THESIS_SUCCESS= "ALL_ADMIN_THESIS_SUCCESS"
export const ALL_ADMIN_THESIS_FAIL= "ALL_ADMIN_THESIS_FAIL"

export const THESIS_COUNT_REQUEST= "THESIS_COUNT_REQUEST"
export const THESIS_COUNT_SUCCESS= "THESIS_COUNT_SUCCESS"
export const THESIS_COUNT_FAIL= "THESIS_COUNT_FAIL"

export const NEW_THESIS_REQUEST = 'NEW_THESIS_REQUEST'
export const NEW_THESIS_SUCCESS = 'NEW_THESIS_SUCCESS'
export const NEW_THESIS_RESET = 'NEW_THESIS_RESET'
export const NEW_THESIS_FAIL = 'NEW_THESIS_FAIL'

export const UPDATE_THESIS_REQUEST = 'UPDATE_THESIS_REQUEST'
export const UPDATE_THESIS_SUCCESS = 'UPDATE_THESIS_SUCCESS'
export const UPDATE_THESIS_RESET = 'UPDATE_THESIS_RESET'
export const UPDATE_THESIS_FAIL = 'UPDATE_THESIS_FAIL'

export const DELETE_THESIS_REQUEST = 'DELETE_THESIS_REQUEST'
export const DELETE_THESIS_SUCCESS = 'DELETE_THESIS_SUCCESS'
export const DELETE_THESIS_RESET = 'DELETE_THESIS_RESET'
export const DELETE_THESIS_FAIL = 'DELETE_THESIS_FAIL'

export const DEACTIVATE_THESIS_REQUEST = 'DEACTIVATE_THESIS_REQUEST'
export const DEACTIVATE_THESIS_SUCCESS = 'DEACTIVATE_THESIS_SUCCESS'
export const DEACTIVATE_THESIS_RESET = 'DEACTIVATE_THESIS_RESET'
export const DEACTIVATE_THESIS_FAIL = 'DEACTIVATE_THESIS_FAIL'

export const ACTIVATE_THESIS_REQUEST = 'ACTIVATE_THESIS_REQUEST'
export const ACTIVATE_THESIS_SUCCESS = 'ACTIVATE_THESIS_SUCCESS'
export const ACTIVATE_THESIS_RESET = 'ACTIVATE_THESIS_RESET'
export const ACTIVATE_THESIS_FAIL = 'ACTIVATE_THESIS_FAIL'

export const THESIS_DETAILS_REQUEST = 'THESIS_DETAILS_REQUEST'
export const THESIS_DETAILS_SUCCESS = 'THESIS_DETAILS_SUCCESS'
export const THESIS_DETAILS_FAIL = 'THESIS_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
