
export const ALL_THESIS_REQUEST= "ALL_THESIS_REQUEST"
export const ALL_THESIS_SUCCESS= "ALL_THESIS_SUCCESS"
export const ALL_THESIS_FAIL= "ALL_THESIS_FAIL"

export const THESIS_COUNT_REQUEST= "THESIS_COUNT_REQUEST"
export const THESIS_COUNT_SUCCESS= "THESIS_COUNT_SUCCESS"
export const THESIS_COUNT_FAIL= "THESIS_COUNT_FAIL"

export const THESIS_DETAILS_REQUEST = 'THESIS_DETAILS_REQUEST'
export const THESIS_DETAILS_SUCCESS = 'THESIS_DETAILS_SUCCESS'
export const THESIS_DETAILS_FAIL = 'THESIS_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
