
export const ALL_THESIS_REQUEST= "ALL_THESIS_REQUEST"
export const ALL_THESIS_SUCCESS= "ALL_THESIS_SUCCESS"
export const ALL_THESIS_FAIL= "ALL_THESIS_FAIL"

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
